# Generated by Django 5.0.3 on 2024-03-27 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerTypeQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('correctOption', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleCorrectQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=1)),
                ('option2', models.CharField(max_length=1)),
                ('option3', models.CharField(max_length=1)),
                ('option4', models.CharField(max_length=1)),
                ('correctOptions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCorrectQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=1)),
                ('option2', models.CharField(max_length=1)),
                ('option3', models.CharField(max_length=1)),
                ('option4', models.CharField(max_length=1)),
                ('correctOption', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='qRefTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1_set', to='questions.singlecorrectq')),
                ('q10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q10_set', to='questions.singlecorrectq')),
                ('q11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q11_set', to='questions.singlecorrectq')),
                ('q12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q12_set', to='questions.singlecorrectq')),
                ('q13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q13_set', to='questions.singlecorrectq')),
                ('q14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q14_set', to='questions.singlecorrectq')),
                ('q15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q15_set', to='questions.singlecorrectq')),
                ('q16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q16_set', to='questions.singlecorrectq')),
                ('q17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q17_set', to='questions.singlecorrectq')),
                ('q18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q18_set', to='questions.singlecorrectq')),
                ('q19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q19_set', to='questions.singlecorrectq')),
                ('q2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q2_set', to='questions.singlecorrectq')),
                ('q20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q20_set', to='questions.singlecorrectq')),
                ('q21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q21_set', to='questions.singlecorrectq')),
                ('q22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q22_set', to='questions.singlecorrectq')),
                ('q23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q23_set', to='questions.singlecorrectq')),
                ('q24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q24_set', to='questions.singlecorrectq')),
                ('q25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q25_set', to='questions.singlecorrectq')),
                ('q26', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q26_set', to='questions.singlecorrectq')),
                ('q27', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q27_set', to='questions.singlecorrectq')),
                ('q28', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q28_set', to='questions.singlecorrectq')),
                ('q29', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q29_set', to='questions.singlecorrectq')),
                ('q3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q3_set', to='questions.singlecorrectq')),
                ('q30', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q30_set', to='questions.singlecorrectq')),
                ('q4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q4_set', to='questions.singlecorrectq')),
                ('q5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q5_set', to='questions.singlecorrectq')),
                ('q6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q6_set', to='questions.singlecorrectq')),
                ('q7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q7_set', to='questions.singlecorrectq')),
                ('q8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q8_set', to='questions.singlecorrectq')),
                ('q9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q9_set', to='questions.singlecorrectq')),
            ],
        ),
    ]
