# Generated by Django 5.0.3 on 2024-03-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qreftable',
            name='q1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q1_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q10_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q11_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q12_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q13_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q14_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q15_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q16_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q17_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q18_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q19_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q2_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q20_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q21_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q22_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q23_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q24_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q25_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q26_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q27_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q28_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q29_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q3_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q30_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q4_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q5_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q6_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q7_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q8_set', to='questions.singlecorrectq'),
        ),
        migrations.AlterField(
            model_name='qreftable',
            name='q9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q9_set', to='questions.singlecorrectq'),
        ),
    ]
