# Generated by Django 5.0.3 on 2024-03-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_qtype_alter_qreftable_q1_alter_qreftable_q10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integertypeq',
            name='correctOption',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)]),
        ),
        migrations.AlterField(
            model_name='multiplecorrectq',
            name='correctOptions',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '1,2'), ('6', '1,3'), ('7', '1,4'), ('8', '2,3'), ('9', '2,4'), ('10', '3,4'), ('11', '1,2,3'), ('12', '1,2,4'), ('13', '1,3,4'), ('14', '2,3,4'), ('15', '1,2,3,4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='singlecorrectq',
            name='correctOption',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
    ]
