# Generated by Django 5.0.3 on 2024-03-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_integertypeq_correctoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integertypeq',
            name='correctOption',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
