# Generated by Django 5.0.3 on 2024-03-27 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100)),
                ('numberOfQuestion', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('qRefTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.qreftable')),
            ],
        ),
        migrations.CreateModel(
            name='testResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=20)),
                ('s2', models.CharField(max_length=20)),
                ('s3', models.CharField(max_length=20)),
                ('s4', models.CharField(max_length=20)),
                ('s5', models.CharField(max_length=20)),
                ('s6', models.CharField(max_length=20)),
                ('s7', models.CharField(max_length=20)),
                ('s8', models.CharField(max_length=20)),
                ('s9', models.CharField(max_length=20)),
                ('s10', models.CharField(max_length=20)),
                ('s11', models.CharField(max_length=20)),
                ('s12', models.CharField(max_length=20)),
                ('s13', models.CharField(max_length=20)),
                ('s14', models.CharField(max_length=20)),
                ('s15', models.CharField(max_length=20)),
                ('s16', models.CharField(max_length=20)),
                ('s17', models.CharField(max_length=20)),
                ('s18', models.CharField(max_length=20)),
                ('s19', models.CharField(max_length=20)),
                ('s20', models.CharField(max_length=20)),
                ('s21', models.CharField(max_length=20)),
                ('s22', models.CharField(max_length=20)),
                ('s23', models.CharField(max_length=20)),
                ('s24', models.CharField(max_length=20)),
                ('s25', models.CharField(max_length=20)),
                ('s26', models.CharField(max_length=20)),
                ('s27', models.CharField(max_length=20)),
                ('s28', models.CharField(max_length=20)),
                ('s29', models.CharField(max_length=20)),
                ('s30', models.CharField(max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BooleanField()),
                ('r2', models.BooleanField()),
                ('r3', models.BooleanField()),
                ('r4', models.BooleanField()),
                ('r5', models.BooleanField()),
                ('r6', models.BooleanField()),
                ('r7', models.BooleanField()),
                ('r8', models.BooleanField()),
                ('r9', models.BooleanField()),
                ('r10', models.BooleanField()),
                ('r11', models.BooleanField()),
                ('r12', models.BooleanField()),
                ('r13', models.BooleanField()),
                ('r14', models.BooleanField()),
                ('r15', models.BooleanField()),
                ('r16', models.BooleanField()),
                ('r17', models.BooleanField()),
                ('r18', models.BooleanField()),
                ('r19', models.BooleanField()),
                ('r20', models.BooleanField()),
                ('r21', models.BooleanField()),
                ('r22', models.BooleanField()),
                ('r23', models.BooleanField()),
                ('r24', models.BooleanField()),
                ('r25', models.BooleanField()),
                ('r26', models.BooleanField()),
                ('r27', models.BooleanField()),
                ('r28', models.BooleanField()),
                ('r29', models.BooleanField()),
                ('r30', models.BooleanField()),
                ('score', models.DecimalField(decimal_places=10, max_digits=10)),
                ('testResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.testresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
