# Generated by Django 5.0.3 on 2024-04-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_alter_multiplecorrectq_correctoptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100)),
                ('numberOfQuestion', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('qRefTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.qreftable')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
            ],
        ),
        migrations.CreateModel(
            name='testResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(default='', max_length=20)),
                ('s2', models.CharField(default='', max_length=10)),
                ('s3', models.CharField(default='', max_length=10)),
                ('s4', models.CharField(default='', max_length=10)),
                ('s5', models.CharField(default='', max_length=10)),
                ('s6', models.CharField(default='', max_length=10)),
                ('s7', models.CharField(default='', max_length=10)),
                ('s8', models.CharField(default='', max_length=10)),
                ('s9', models.CharField(default='', max_length=10)),
                ('s10', models.CharField(default='', max_length=10)),
                ('s11', models.CharField(default='', max_length=10)),
                ('s12', models.CharField(default='', max_length=10)),
                ('s13', models.CharField(default='', max_length=10)),
                ('s14', models.CharField(default='', max_length=10)),
                ('s15', models.CharField(default='', max_length=10)),
                ('s16', models.CharField(default='', max_length=10)),
                ('s17', models.CharField(default='', max_length=10)),
                ('s18', models.CharField(default='', max_length=10)),
                ('s19', models.CharField(default='', max_length=10)),
                ('s20', models.CharField(default='', max_length=10)),
                ('s21', models.CharField(default='', max_length=10)),
                ('s22', models.CharField(default='', max_length=10)),
                ('s23', models.CharField(default='', max_length=10)),
                ('s24', models.CharField(default='', max_length=10)),
                ('s25', models.CharField(default='', max_length=10)),
                ('s26', models.CharField(default='', max_length=10)),
                ('s27', models.CharField(default='', max_length=10)),
                ('s28', models.CharField(default='', max_length=10)),
                ('s29', models.CharField(default='', max_length=10)),
                ('s30', models.CharField(default='', max_length=10)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(default=0)),
                ('tf', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userresponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.CharField(default='', max_length=100)),
                ('qid', models.IntegerField(default=0)),
                ('sol', models.CharField(default='', max_length=100)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
